 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.9.0
     steps:
       - checkout
       - run: python -m unittest
       - run: python setup.py bdist --format=tar
       - store_artifacts:
          path: /dist
